# Generated by Django 5.1.dev20231212045133 on 2023-12-14 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2023, 12, 28))),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('min_age', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('sp_english', models.BooleanField()),
                ('sp_georgian', models.BooleanField()),
                ('sp_spanish', models.BooleanField()),
                ('sp_japanese', models.BooleanField()),
                ('image', models.CharField(max_length=50)),
                ('tours', models.ManyToManyField(to='testapp.tour')),
            ],
        ),
    ]
