# Generated by Django 5.1.dev20231212045133 on 2023-12-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name',
            field=models.CharField(default='Miguel', max_length=50),
        ),
    ]
