# Generated by Django 5.1.dev20231212045133 on 2023-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_guide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='audio_file',
            field=models.FileField(default='tests.py', upload_to='uploads/'),
        ),
    ]
