# Generated by Django 5.1.dev20231212045133 on 2023-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_tour_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField(default=6)),
                ('field2', models.IntegerField(default=7)),
            ],
        ),
    ]
