# Generated by Django 5.1.dev20231212045133 on 2023-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_yourmodel_field1_alter_yourmodel_field2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='audio_file',
            new_name='audio_desc',
        ),
        migrations.AddField(
            model_name='tour',
            name='audio_name',
            field=models.FileField(default='tests.py', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='audio_price',
            field=models.FileField(default='tests.py', upload_to='static/'),
        ),
    ]
