# Generated by Django 5.1.dev20231212045133 on 2023-12-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_rename_audio_file_tour_audio_desc_tour_audio_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='take your dream and hold it as it is your life', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
