# Generated by Django 5.1.dev20231212045133 on 2023-12-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_test_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='field1',
        ),
    ]
